server:
  port: 8081

spring:
  application:
    name: TransactionProducer
  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: admin
    password: adminpass
    embedded:
      queues: transactions